version: '3.1'

services:
 drupal:
   build: ./
   container_name: 'mon_container_drupal'
   ports:
     - 8099:80
   volumes:
     - ./site/html:/var/www/html  

 db:
   image: mysql
   container_name: 'mydb'
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   environment:
     MYSQL_DATABASE: drupal
     MYSQL_USER: drupal
     MYSQL_PASSWORD: drupal
     MYSQL_ROOT_PASSWORD: example
   volumes:
     - ./data/mysql:/var/lib/mysql  

 adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080